server:
  port: 8888
spring:
  #main:
    #web-application-type: reactive
  application:
   name: config-server
  #secutiry:
   # user:
      #name: dvivasva
      #password: nttdata
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dvivasva/config-yam.git
          deafult-label: main
          #username:
          #password:

 #profiles:
     #active:


