spring:
  #main:
    #web-application-type: reactive
  application:
   name: config-server
  #secutiry:
   # user:
      #name: dvivasva
      #password: nttdata
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dvivasva/config-server.git
          deafult-label: main
          #username:
          #password:

  #profiles:
     #active:
  data:
    mongodb:
      uri: ${data.mongodb.uri}
server:
  port: 8888

